#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1090
source "$SCRIPT_DIR/lib.sh"

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
  shift
fi

usage() {
  cat <<'USAGE'
Usage: gdops metadata-check [--dry-run] <source|bin>

Checks that .SRCINFO matches the PKGBUILD generated by makepkg --printsrcinfo.
USAGE
}

case "${1:-}" in
  -h|--help|help)
    usage
    exit 0
    ;;
esac

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

case "$1" in
  source|src)
    repo_dir="$SRC_DIR"
    label="source"
    ;;
  bin|binary)
    repo_dir="$BIN_DIR"
    label="binary"
    ;;
  *)
    usage
    exit 1
    ;;
esac

require_dirs
require_file "$repo_dir/PKGBUILD"
require_file "$repo_dir/.SRCINFO"

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "Dry run: would compare generated .SRCINFO for $label package"
  exit 0
fi

require_cmd makepkg
require_cmd diff

tmp_srcinfo="$(mktemp)"
trap 'rm -f "$tmp_srcinfo"' EXIT

(
  cd "$repo_dir"
  makepkg --printsrcinfo
) > "$tmp_srcinfo"

if ! diff -u "$repo_dir/.SRCINFO" "$tmp_srcinfo"; then
  die "$repo_dir/.SRCINFO is out of sync with PKGBUILD"
fi

log "Metadata check passed for $label package"
